<?php

class ResponseProvider
{
	public static function getMasterpassDebitResponse()
	{
		return base64_encode("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><payment xmlns=\"http://www.elastic-payments.com/schema/payment\"><merchant-account-id>ff1cc720-e73d-408d-acd4-9cbb491c1b3c</merchant-account-id><transaction-id>dfcd8bee-1323-4960-b05a-388b64799be2</transaction-id><request-id>c57a8da8-085d-5058-b43f-412ce5132f3e</request-id><transaction-type>debit</transaction-type><transaction-state>success</transaction-state><completion-time-stamp>2016-11-01T07:42:57.000Z</completion-time-stamp><statuses><status code=\"201.0000\" description=\"The resource was successfully created.\" severity=\"information\"/></statuses><requested-amount currency=\"SGD\">4.00</requested-amount><parent-transaction-id>05e44225-424a-441a-a425-3cfc71ca0b82</parent-transaction-id><account-holder><email>kim@email.com</email><phone>12345676</phone><address><street1>test1</street1><city>singapore</city><country>SG</country><postal-code>123456</postal-code></address></account-holder><card><expiration-month>1</expiration-month><expiration-year>2020</expiration-year><card-type>mastercard</card-type></card><card-token><token-id>5266048063690014</token-id><masked-account-number>520474******0014</masked-account-number></card-token><custom-fields><custom-field field-name=\"elastic-api.merchant-origin\" field-value=\"http://localhost/shop/masterpass/precheckout/\"/></custom-fields><payment-methods><payment-method name=\"masterpass\"/></payment-methods><api-id>---</api-id><processing-redirect-url>http://localhost/shop/rest/masterpass/requestcheckoutresponse/?</processing-redirect-url><cancel-redirect-url>http://localhost/shop/rest/masterpass/requestcheckoutresponse/?</cancel-redirect-url><fail-redirect-url>http://localhost/shop/rest/masterpass/requestcheckoutresponse/?</fail-redirect-url><success-redirect-url>http://localhost/shop/rest/masterpass/requestcheckoutresponse/?</success-redirect-url><wallet><provider-ref>a466w42-7th98g-iuoen57j-1-iuz6h732-6xoc</provider-ref><provider-transaction-id>a466w42-7th98g-iuoen57j-1-iuz6h732-6xoc</provider-transaction-id></wallet><provider-transaction-reference-id>27164948457843568161</provider-transaction-reference-id></payment>");
	}

    public static function getPaypalSuccessResponse()
    {
        return base64_encode("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?> <payment xmlns=\"http://www.elastic-payments.com/schema/payment\"> <merchant-account-id>be17476f-1a0c-442e-8841-70e33996c0aa</merchant-account-id> <transaction-id>4e3b9261-4a82-47df-8795-ae5353dd9ee3</transaction-id> <request-id>8f2906ea-21ba-4afb-be75-54dd4439403a</request-id> <transaction-type>authorization</transaction-type> <transaction-state>success</transaction-state> <completion-time-stamp>2018-04-11T09:29:27.000Z</completion-time-stamp> <statuses> <status code=\"201.0000\" description=\"The resource was successfully created.\" severity=\"information\" provider-transaction-id=\"2EV690760Y9874511\"/> </statuses> <requested-amount currency=\"EUR\">1.15</requested-amount> <parent-transaction-id>f605cbe3-5e05-4de7-b854-ce37445d00e6</parent-transaction-id> <account-holder> <first-name>Wirecardbuyer</first-name> <last-name>Spintzyk</last-name> <email>paypal.buyer2@wirecard.com</email> </account-holder> <descriptor>customerStatement 18009998888</descriptor> <custom-fields/> <payment-methods> <payment-method name=\"paypal\"/> </payment-methods> <api-id>---</api-id> <cancel-redirect-url>https://demoshop-test.wirecard.com/demoshop/#!/cancel</cancel-redirect-url> <success-redirect-url>https://demoshop-test.wirecard.com/demoshop/#!/success</success-redirect-url> <fail-redirect-url>https://demoshop-test.wirecard.com/demoshop/#!/error</fail-redirect-url> <wallet> <account-id>ZNKTXUBNSQE2Y</account-id> </wallet> </payment>");
    }

    public static function  getPaypalFailureResponse()
    {
        return base64_encode("<?xml version=\"1.0\" encoding=\"utf-8\" standalone=\"yes\"?> <payment xmlns=\"http://www.elastic-payments.com/schema/payment\" xmlns:ns2=\"http://www.elastic-payments.com/schema/epa/transaction\"> <merchant-account-id>be17476f-1a0c-442e-8841-70e33996c0aa</merchant-account-id> <transaction-id>7f26b332-eb32-48fc-8580-6ad162713804</transaction-id> <request-id>f997b1dc-c996-431a-a403-bbeab26f873c</request-id> <transaction-type>authorization</transaction-type> <transaction-state>failed</transaction-state> <completion-time-stamp>2018-04-12T09:18:03.000Z</completion-time-stamp> <statuses> <status code=\"400.1013\" description=\"The Requested Amount is below the minimum required for this Merchant Account.  Please check your input and try again.\" severity=\"error\" /> </statuses> <requested-amount currency=\"EUR\">0.00</requested-amount> <account-holder> <first-name>Wirecardbuyer</first-name> <last-name>Spintzyk</last-name> <email>paypal.buyer2@wirecard.com</email> </account-holder> <shipping> <first-name>Jack</first-name> <last-name>Jones</last-name> <phone>+49123123123</phone> <address> <street1>123 anystreet</street1> <city>Brantford</city> <country>CA</country> <postal-code>M4P1E8</postal-code> </address> </shipping> <order-number>180412111803918</order-number> <descriptor>customerStatement 18009998888</descriptor> <payment-methods> <payment-method name=\"paypal\" /> </payment-methods> <cancel-redirect-url>https://demoshop-test.wirecard.com/demoshop/#!/cancel</cancel-redirect-url> <success-redirect-url>https://demoshop-test.wirecard.com/demoshop/#!/success</success-redirect-url> </payment>");
    }
}